title: Gaurav Singh
email: gaurav.singh@columbia.edu
description: >- 
  Portfolio website for Gaurav Singh, Data Scientist and AI Engineer.
baseurl: ""
url: "https://gaursin13.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Custom dark mode
minima:
  skin: dark
  social_links:
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/gauravrasingh/" }
    - { platform: github,    user_url: "https://github.com/gaursin13" }
